name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - name: Install DrWatson
        run: julia --project=. -e 'using Pkg; Pkg.add("DrWatson")'
      - name: Run tests
        run: >
          julia --project=. --color=yes test/runtests.jl

      - name: Generate documentation and deploy
        env: # needed for pushing to gh-pages branch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          # If your documentation deployment pushes to a protected branch (like gh-pages) and needs to authenticate as more than just the default GitHub Actions bot,
          # or if you want to deploy from forks or private repos, you may need a DOCUMENTER_KEY.
          # For public repos deploying from main with GITHUB_TOKEN, you usually do NOT need DOCUMENTER_KEY.
          # See: https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#GitHub-Actions
