name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:  # Manual trigger for documentation deployment
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      
      # Enhanced caching with multiple fallback keys
      - name: Cache Julia packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.julia
            ~/.julia/compiled
            ~/.julia/packages
          key: julia-${{ runner.os }}-${{ matrix.version }}-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}
          restore-keys: |
            julia-${{ runner.os }}-${{ matrix.version }}-
            julia-${{ runner.os }}-
      
      # Fallback Julia cache action with continue-on-error
      - uses: julia-actions/cache@v1
        continue-on-error: true
        
      - uses: julia-actions/julia-buildpkg@v1
        continue-on-error: true
        
      # If build fails, retry with clean environment
      - name: Retry build on failure
        if: failure()
        run: |
          julia --project=. -e "using Pkg; Pkg.instantiate()"
          
      - name: Run tests
        run: >
          julia --project=. --color=yes -e "include(\"test/runtests.jl\")"

  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: test
    # Only deploy on push to main (not on PRs) OR manual trigger
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
          arch: x64
          
      # Enhanced caching for docs job
      - name: Cache Julia packages (docs)
        uses: actions/cache@v4
        with:
          path: |
            ~/.julia
            ~/.julia/compiled
            ~/.julia/packages
          key: julia-docs-${{ runner.os }}-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}
          restore-keys: |
            julia-docs-${{ runner.os }}-
            julia-${{ runner.os }}-
            
      - uses: julia-actions/cache@v1
        continue-on-error: true
        
      - uses: julia-actions/julia-buildpkg@v1
        continue-on-error: true
        
      # Retry build for docs if needed
      - name: Retry docs build on failure
        if: failure()
        run: |
          julia --project=. -e "using Pkg; Pkg.instantiate()"

      - name: Generate documentation and deploy
        run: >
          julia --project=. --color=yes docs/make.jl
        env: # needed for pushing to gh-pages branch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
          # Configure the subdirectory for this repository
          DOCUMENTER_DEPLOY_SUBDIRECTORY: "math_foundations"
